---
# Sample sheet
samplesheet: "organoid_sample_sheet.tsv"

# Output location
out_dir: "/pmglocal/jfr2137/temp/absolutecn_output/"

# Bin sizes
# By default any in [1,5,15,30,50,100,500,1000]
bins:
- 30
project_name: "su2c_organoids"

# Pipeline parameters
purity_cutoff: 0.15

# Not implemented
#custom_bin: false
#custom_bin_folder: "/custom_bin_data/"
